import manifest from "@/public/art/manifest.json";

// ART1 — one component renders every brand-art placement (public/art/*).
//
// Why a <picture> and not next/image: the assets are ALREADY optimized (AVIF q80
// + WebP, 1x/2x, generated by scripts/generate-art.mjs). next/image would re-pipe
// static files through the optimizer for no gain and can't emit a true
// AVIF→WebP <picture> fallback. A hand-rolled <picture> gives real format
// fallback AND lets us set explicit width/height so the box never reflows (zero
// CLS). Consistency across placements is what makes the set read as premium (ART2).
//
// Every asset ships AVIF + WebP; only og:card also ships a PNG (social scrapers),
// which is consumed server-side, not here — so this component only needs the two
// modern formats, which every browser rukMoney targets supports.

type Asset = {
  name: string;
  placement: string;
  display: { w: number; h: number };
  scales: number[];
  files: string[];
};

const BY_NAME = new Map<string, Asset>(
  (manifest.assets as Asset[]).map((a) => [a.name, a]),
);

export function ArtImage({
  name,
  alt,
  className,
  priority = false,
  sizes,
}: {
  name: string;
  alt: string;
  className?: string;
  // Above-the-fold art (login hero) should load eagerly; everything else lazy.
  priority?: boolean;
  // Optional max render width so the browser can pick 1x vs 2x sensibly.
  sizes?: string;
}) {
  const a = BY_NAME.get(name);
  if (!a) return null; // asset was pruned/renamed — render nothing, never a broken box.

  const { w, h } = a.display;
  const has2x = a.scales.includes(2);
  const srcSet = (ext: "avif" | "webp") =>
    has2x
      ? `/art/${name}@1x.${ext} 1x, /art/${name}@2x.${ext} 2x`
      : `/art/${name}@1x.${ext}`;

  return (
    <picture>
      <source type="image/avif" srcSet={srcSet("avif")} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet("webp")} sizes={sizes} />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`/art/${name}@1x.webp`}
        alt={alt}
        width={w}
        height={h}
        className={className}
        loading={priority ? "eager" : "lazy"}
        decoding={priority ? "auto" : "async"}
        // @ts-expect-error fetchpriority is valid HTML but not yet in React's types
        fetchpriority={priority ? "high" : undefined}
        draggable={false}
      />
    </picture>
  );
}
